# project setup
library(usethis)
create_project("/workspace/workspace_pipelines/baiocchi_long")
use_mit_license("Brad Blaser")
use_package("blaseRtools", type = "imports")
use_package("tidyverse", type = "imports")
use_package("monocle3", type = "imports")
use_package("cowplot", type = "imports")
use_package("circlize", type = "imports")
use_package("ComplexHeatmap", type = "imports")
use_package("readxl", type = "imports")
use_readme_md()
use_news_md()
use_git()
use_data()
use_data_raw()
